Camera_app/urls.py
from django.urls import path
from .views import *

app_name="Camera_app"

urlpatterns = [
	path('fileupload/', fileUpload, name="fileupload"),
	# path('photo/',forbidden_location,name="photo")
]

Home/urls.py
from django.urls import path

from Home.views import Index

app_name="Home_app"

urlpatterns = [
    path('',Index, name= "Home")
]

P_ZONE_NOTICE/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('Home.urls')),
    path('admin/', admin.site.urls),
    path('Camera/',include('Camera_app.urls')),
    path('geolocation/',include('geolocation.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geolocation/urls.py
from django.contrib.auth import admin
from django.urls import path, include

from geolocation.views import find_P_ZONE

app_name="geolocation_app"

urlpatterns = [
    path('/',find_P_ZONE, name= "geolocation")
]

Camera_app/models.py
from django.db import models

# Create your models here.
class FileUpload(models.Model):
    title = models.TextField(max_length=40, null=True)
    imgfile = models.ImageField(null=False, upload_to="", blank=True)
    content = models.TextField(null=True)

    def __str__(self):
        return self.title

Home/models.py
from django.db import models

# Create your models here.

geolocation/models.py
from django.db import models

# Create your models here.

Camera_app/forms.py
from django.forms import ModelForm
from .models import FileUpload

class FileUploadForm(ModelForm):
    class Meta:
        model = FileUpload
        fields = ['title', 'imgfile', 'content']

Camera_app/views.py
import json
import os.path
import uuid
from typing import IO
import json

import requests

import pymysql
import requests
from django.http import HttpResponse
from django.shortcuts import render, redirect

from P_ZONE_NOTICE.settings import MARIADB
from .forms import FileUploadForm



def fileUpload(request):

    # DB requirement
    host = MARIADB['default']["DB_HOST"]
    user = MARIADB['default']["DB_USER"]
    db = MARIADB['default']["DB_NAME"]
    password= MARIADB['default'][ 'DB_PASSWORD']

    connect = pymysql.connect(host=host, user=user, password=password, port=3306, db=db)
    cursor = connect.cursor()



    # Request Post일때
    if request.method == 'POST':
        long = float(request.POST.get('long'))
        lat = float(request.POST.get('lat'))
        img = request.FILES['Camera']

        # geo
        # 행정동 불러오기
        sql = "select dongcode from dong"
        cursor.execute(sql)
        dong_list = [row[0] for row in cursor.fetchall()]
        
        
        ## tmap appkey 설정 필요
        # 현 위치데이터를 dong으로 변환 및 비교
        API = "https://apis.openapi.sk.com/tmap/geo/reversegeocoding?version=1"
        payload = {"appKey": "l7xx0ffb87c22bdb45ae8facaeeb7958ad36", "lon": long, "lat": lat} 
        res = requests.get(API, params=payload)
        dongCode = int(json.loads(res.text)["addressInfo"]["legalDongCode"][5:8])
        if dongCode not in dong_list:
            print("여기는 강남구가 아님")
        else:
            print("여기는 강남구")
            print(dongCode)



        ## MODEL 서버와 통신 후 Response
        url = 'http://test-fastmodel:8000/file/store'
        upload = {'file': img}

        context = requests.post(url, files=upload).json()
        # context=dict()
        context["lat"] = lat
        context["long"] = long
        context["length"] = 0
        context["kinds"] = set()

        
        # criteria를 기준으로 근처의 주차 금지구역 확인
        from haversine import haversine
        criteria = 100
        place_list = []
        sql = f"""SELECT c.type, c.latitude, c.longitude
                  FROM cautionzone c
                  WHERE c.dongcode={dongCode}"""
        cursor.execute(sql)
        for row in cursor.fetchall():
            cz_lat=float(row[1])
            cz_long=float(row[2])
            distance = haversine((lat, long), (cz_lat, cz_long), unit="m")
            if distance < criteria:
                print(row, distance)
                place_list.append({"type": row[0], "latitude": cz_lat, "longitude": cz_long})
                if row[0] == "bus":
                    context["kinds"].add(4)
                    context["length"] = context["length"]+1
                elif row[0] == "fire":
                    context["kinds"].add(5)
                    context["length"] = context["length"]+1
                elif row[0] == "taxi":
                    context["kinds"].add(6)
                    context["length"] = context["length"]+1
                elif row[0] == "subway":
                    context["kinds"].add(7)
                    context["length"] = context["length"] + 1
                elif row[0] == "children":
                    context["kinds"].add(8)
                    context["length"] = context["length"] + 1



        #  // 주차가능구역 확인
        sql = f"""SELECT p.type, p.latitude, p.longitude
                  FROM parkingzone p
                  WHERE p.dongcode={dongCode}"""

        cursor.execute(sql)
        for row in cursor.fetchall():
            pz_lat=float(row[1])
            pz_long=float(row[2])
            distance = haversine((lat, long), (pz_lat, pz_long), unit="m")
            if distance < criteria:
                print(row)
                place_list.append({"type": row[0], "latitude": pz_lat, "longitude": pz_long})

        context["placeList"] = place_list
        print(context)
        return  render(request,'result.html',context)


    ## request method가 Get일때 (Home 페이지 html 호출)
    else:
        from django.urls import reverse
        from Home.views import Index
        return reverse(Index)
        # fileuploadForm = FileUploadForm
        # context = {
        #
        #     'fileuploadForm': fileuploadForm,
        # }
        # return render(request, 'fileupload.html', context)

Home/views.py
from django.shortcuts import render

# Create your views here.


def Index(request):
    context={}
    return render(request,'Home.html',context)

geolocation/views.py
from django.shortcuts import render

# Create your views here.
import os
import pymysql
import json

from django.http import HttpResponse
from django.shortcuts import render
import requests
import json
import time

from P_ZONE_NOTICE.settings import MARIADB


def find_P_ZONE(request):

    host = MARIADB['default']["DB_HOST"]
    user = MARIADB['default']["DB_USER"]
    password = MARIADB['default']["DB_PASSWORD"]
    db = MARIADB['default']["DB_NAME"]
    # try:
    #     host =os.environ("DB_HOST")
    #     user =os.environ("DB_USER")
    #     password=os.environ("DB_PASSWORD")
    #     db=os.environ("DB_NAME")
    # except:
    #     HttpResponse("NO PARAMETER")
    #
    connect = pymysql.connect(host=host, user=user, password=password, port=3306, db=db)
    cursor = connect.cursor()
    sql = "select * from parkingpzone"
    cursor.execute(sql)
    rows = cursor.fetchall()
    # parkingzone = pd.read_csv(os.path.join(BASE_DIR,'parkingzone.csv'))

    url = f"https://apis.openapi.sk.com/tmap/routes/pedestrian?version=1"

    headers = {
        "appkey": "l7xx0ffb87c22bdb45ae8facaeeb7958ad36 ",
    }

    # 현재 위치
    longitude = float(request.GET.get('longitude'))
    latitude = float(request.GET.get('latitude'))


    minTime = 1000000000000
    for idx,row in enumerate(rows):  # row
        time.sleep(0.6)
        payload = {
            "startX": longitude,
            "startY": latitude,
            "endX": row[3], #longitude
            "endY": row[2], #
            "startName": "현위치",
            "endName": "주차장"
        }

        res = requests.post(url, json=payload, headers=headers)

        jsonObj = json.loads(res.text)

        if jsonObj["features"][0]["properties"]["totalTime"] < minTime:
            nearest = jsonObj
            minTime = jsonObj["features"][0]["properties"]["totalTime"]


    print(nearest)

    context = {
        "nearest": json.dumps(nearest)
    }
    return render(request, 'geolocation.html', context)

Camera_app/templates/fileupload.html
{% extends 'base.html' %}

{% block content %}
<!--<body onload="geolocation();">-->
<section class="page-section" >
    <form method="POST" action="{% url 'Camera_app:fileupload' %}" enctype="multipart/form-data">
        {% csrf_token %}
<!--        <input type="submit" class="btn btn-primary col-12" value="제출">-->
        <input type="file" accept="image/*;capture=camera"  name="Camera" >
        <input type="hidden" name="lat" id="lat">
        <input type="hidden" name="long" id="long">

        <button  type="submit" >전송</button>
<!--        <button type="button" onClick="upload()">Save</button>-->
    </form>
</section>

<section class="page-section" >
    <div class="container">
        <!-- Contact Section Heading-->
        <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">서비스 종류</h2>
        <!-- Icon Divider-->
        <div class="divider-custom">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>
        <!-- Contact Section Form-->
        <div class="row justify-content-center">
            <div class="d-flex justify-content-center">
                <a src="{% url 'Camera_app:fileupload' %}" class="btn btn-primary btn-xl" style="margin-bottom:2%" id="distinguishButton" >주차가능구역 판별</a >
                </div>
            <div class="d-flex justify-content-center">
                <a src="{% url 'geolocation_app:geolocation' %}" class="btn btn-primary btn-xl" id="guideButton" >가까운 전동킥보드 주차장 안내</a >
                </div>
            </div><!--button태그의 class에서 disabled 삭제-->
        </div>
        
        </div>
        
    </div>
    </section>

<!--</body>-->

{% endblock content%}

{% block javascripts %}
    <script src="https://code.getmdl.io/1.3.0/material.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dialog-polyfill/0.5.0/dialog-polyfill.js" charset="utf-8"></script>
    <script >
    //var url = "{% url 'Camera_app:fileupload' %}";
    // var user_id = "xxxx";
    function success(position) {
        const latitude  = position.coords.latitude;
        const longitude = position.coords.longitude;
        // window.onload = function(){

        document.getElementById("lat").value=latitude;
        document.getElementById("long").value=longitude;
        //}

        //window.location=url + "?" +"latitude=" + latitude + "&" + "longitude=" + longitude;
    }
    function error(position) {
            //HTTPS가 아니거나 위치수집 동의를 안 할 경우
            alert("위치수집 동의를 해주세요")

        }

    if(!navigator.geolocation) {
        //Geolocation API를 지원하지 않는 브라우저일 경우
        alert(" 현 브라우저가 위치수집을 지원하지 않습니다.\n 다른 브라우저를 이용해주세요 ")

        } else {
        //Geolocation API를 지원하는 브라우저일 경우

        var optn = {enableHighAccuracy : true, timeout : 30000, maximumage: 0};
        function geolocation(){
                navigator.geolocation.getCurrentPosition(success, error,optn);
            }
        }
     $(document).ready(geolocation());
    </script>
{% endblock javascripts %}

Camera_app/templates/fileuploadv2.html
{% extends 'base.html' %}

{% block content %}






<div class="container">
    <form method="POST" action="{% url 'Camera_app:fileupload' %}" enctype="multipart/form-data">
        {% csrf_token %}
<!--        {% bootstrap_form fileuploadForm %}-->
<!--        <input type="submit" class="btn btn-primary col-12" value="제출">-->
        <input  type="file" accept="image/*;capture=camera" name="Camera">
        <input type="hidden" name="lat" class="lat">
        <input type="hidden" name="long" class="long">
        <button type="submit" >전송</button>
<!--        <button type="button" onClick="upload()">Save</button>-->
    </form>
    <script onload="geolocation()">
    //var url = "{% url 'Camera_app:fileupload' %}";
    // var user_id = "xxxx";
    function success(position) {
        const latitude  = position.coords.latitude;
        const longitude = position.coords.longitude;
        let x = document.getElementsByClassName("lat")[0];
        let y = document.getElementsByClassName("long")[0];
        x.innerText= latitude;
        y.innerText= longitude;


        //window.location=url + "?" +"latitude=" + latitude + "&" + "longitude=" + longitude;
    }
    function error(position) {
            //HTTPS가 아니거나 위치수집 동의를 안 할 경우
            alert("위치수집 동의를 해주세요")

        }

    if(!navigator.geolocation) {
        //Geolocation API를 지원하지 않는 브라우저일 경우
        alert(" 현 브라우저가 위치수집을 지원하지 않습니다.\n 다른 브라우저를 이용해주세요 ")

        } else {
        //Geolocation API를 지원하는 브라우저일 경우

        var optn = {enableHighAccuracy : true, timeout : 30000, maximumage: 0};
        function geolocation(){navigator.geolocation.getCurrentPosition(success, error,optn);}
        }
    </script>

<!--    <script>-->
<!--    -->
<!--        function(){-->
<!--                const form = new FormData();-->
<!--                form.append('img',img.current.files[0]);-->
<!--                fetch ('{% url 'Camera_app:fileupload' %}',{-->
<!--        method: 'post',-->
<!--        encType: 'multipart/formdata',-->
<!--        body: form-->
<!--        })-->
<!--                }-->
<!--    </script>-->
</div>

{% endblock%}

Camera_app/templates/fileuploadv3.html
{% extends 'base.html' %}

{% block content %}
<!--<body onload="geolocation();">-->
<section class="page-section" id="contact">
    <form method="POST" action="{% url 'Camera_app:fileupload' %}" enctype="multipart/form-data">
        {% csrf_token %}
<!--        <input type="submit" class="btn btn-primary col-12" value="제출">-->
        <input type="file" accept="image/*;capture=camera" name="Camera" >
        <input type="hidden" name="lat" id="lat">
        <input type="hidden" name="long" id="long">

        <button  type="submit" >전송</button>
<!--        <button type="button" onClick="upload()">Save</button>-->
    </form>
</section>
<!--</body>-->

{% endblock content%}

{% block javascripts %}
    <script src="https://code.getmdl.io/1.3.0/material.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dialog-polyfill/0.5.0/dialog-polyfill.js" charset="utf-8"></script>
    <script >
    //var url = "{% url 'Camera_app:fileupload' %}";
    // var user_id = "xxxx";
    function success(position) {
        const latitude  = position.coords.latitude;
        const longitude = position.coords.longitude;
        // window.onload = function(){

        document.getElementById("lat").value=latitude;
        document.getElementById("long").value=longitude;
        //}

        //window.location=url + "?" +"latitude=" + latitude + "&" + "longitude=" + longitude;
    }
    function error(position) {
            //HTTPS가 아니거나 위치수집 동의를 안 할 경우
            alert("위치수집 동의를 해주세요")

        }

    if(!navigator.geolocation) {
        //Geolocation API를 지원하지 않는 브라우저일 경우
        alert(" 현 브라우저가 위치수집을 지원하지 않습니다.\n 다른 브라우저를 이용해주세요 ")

        } else {
        //Geolocation API를 지원하는 브라우저일 경우

        var optn = {enableHighAccuracy : true, timeout : 30000, maximumage: 0};
        function geolocation(){
                navigator.geolocation.getCurrentPosition(success, error,optn);
            }
        }
     $(document).ready(geolocation());
    </script>
{% endblock javascripts %}

Camera_app/templates/result.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://apis.openapi.sk.com/tmap/jsv2?version=1&appKey=l7xx0ffb87c22bdb45ae8facaeeb7958ad36"></script>
<script type="text/javascript">
    var map;
    function initTmap() {
        console.log({{ lat }});
        // 1. 지도 그리기
                map = new Tmapv2.Map("map_div", {
                center : new Tmapv2.LatLng({{ lat }}, {{ long }}), // 현위치 -- 현 위치를 중심으로 지도 만들기
                        width : "100%",
                        height : "400px",
                        zoom : 16,
                        zoomControl : true,
                        scrollwheel : true
                });

                // 2. 마커
        marker = new Tmapv2.Marker(
            {
                position : new Tmapv2.LatLng({{ lat }}, {{ long }}),
                icon : "http://tmapapi.sktelecom.com/upload/tmap/marker/pin_r_m_e.png",
                iconSize : new Tmapv2.Size(24, 38),
                map : map
            }
        );

        var placeList = {{ placeList|safe }};
        for (var i in placeList) {
            marker = new Tmapv2.Marker(
                {
                    position : new Tmapv2.LatLng(placeList[i].latitude, placeList[i].longitude),
                                        icon : "http://tmapapi.sktelecom.com/upload/tmap/marker/pin_r_m_s.png",
                                        iconSize : new Tmapv2.Size(24, 38),
                                        map : map
                }
            );
        }
    }
    $(document).ready(function() {initTmap()});
</script>

<style>
        .result {
        background-color: #1abc9c ;
        border-radius: 0.5rem ;
        padding: 16px 28px;
        align-content: center;
        margin-top: 20px;
        margin-bottom: 20px;
        text-align: center;
        }


</style>

<div class="d-flex justify-content-center">
{% if length <= 5 %}
<div class="result">
    <h3>현재 주차 가능 상태는 "양호" 입니다! </h3>
    <h3>주차 가능 점수 {{length}}점</h3>
</div>
{% elif 5 < length <= 10 %}
<div class="result">
    <h3>현재 주차 가능 상태는 "주의" 입니다! </h3>
    <h3>주차 가능 점수 {{length}}점</h3>
</div>
{% elif 10 < length  %}
<div class="result">
    <h3>현재 주차 가능 상태는 "금지" 입니다! </h3>
    <h3>주차 가능 점수 {{length}}점</h3>
</div>
{% endif %}
</div>

<div class="d-flex justify-content-center">
    <div class="result">
    <img src="{{ uri  }}" alt="이미지" width="400px" height="400px" >
    </div>
</div>

<div class="d-flex justify-content-center">
            <div id="map_div" style="width:100%; height:100%"></div>
</div>


<div class="d-flex justify-content-center">
    <div class="result">
        <div class="container">
  {% if length != 0 %}
    <h3>금지 구역:</h3>
    <br>
    <li>
        {%for ii in kinds %}
            {% if ii == 0 %}
                <ul> 인도 </ul>
            {% endif %}
            {% if ii == 1 %}
                <ul> 횡단보도 </ul>
            {% endif %}
            {% if ii == 2 %}
                <ul> 점자블록 </ul>
            {% endif %}
            {% if ii == 3 %}
                <ul> 자전거 도로 </ul>
            {% endif %}
            {% if ii == 4 %}
                <ul> 버스 정류장 </ul>
            {% endif %}
            {% if ii == 5 %}
                <ul> 소화전 </ul>
            {% endif %}
            {% if ii == 6 %}
                <ul> 택시 정류장 </ul>
            {% endif %}
            {% if ii == 7 %}
                <ul> 지하철역 </ul>
            {% endif %}
            {% if ii == 8 %}
                <ul> 어린이 보호 구역 </ul>
            {% endif %}

        {% endfor %}
    </li>
    {% else %}
        <h2> 금지구역이 없습니다!</h2>
    {% endif %}
<<<<<<< HEAD
            </div>
=======
         </div>
>>>>>>> e56eab3597f380fdfab328c8b9edf5fcda4677e3
        </div>
    </div>
</div>
{% endblock content %}

Camera_app/templates/resultv2.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<div class="container">
  {% if length != 0 %}
    <h2>주차 금지 구역이 있습니다!</h2>
    <hr>
    <h3>금지 구역:</h3>
    <br>
    <li>
        {%for ii in Kinds %}
            {% if ii == 0 %}
                <ul> 자전거 도로 </ul>
            {% endif %}
            {% if ii == 1 %}
                <ul> 횡단보도 </ul>
            {% endif %}
            {% if ii == 2 %}
                <ul> 점자 블록 </ul>
            {% endif %}
        {% endfor %}
    </li>
    {% else %}
        <h2> 금지구역이 없습니다!</h2>
    {% endif %}

</div>

{% endblock %}

Camera_app/templates/resultv3.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://apis.openapi.sk.com/tmap/jsv2?version=1&appKey=l7xx0ffb87c22bdb45ae8facaeeb7958ad36"></script>


<img src="{{ uri }}" alt="이미지" >
    <div class="container">
  {% if length != 0 %}
    <h2>주차 금지 구역이 있습니다!</h2>
    <hr>
    <h3>금지 구역:</h3>
    <br>
    <li>
        {%for ii in Kinds %}
            {% if ii == 0 %}
                <ul> 자전거 도로 </ul>
            {% endif %}
            {% if ii == 1 %}
                <ul> 횡단보도 </ul>
            {% endif %}
            {% if ii == 2 %}
                <ul> 점자 블록 </ul>
            {% endif %}
        {% endfor %}
    </li>
    {% else %}
        <h2> 금지구역이 없습니다!</h2>
    {% endif %}
</div>

{% endblock %}

Home/templates/Home.html
{% extends 'base.html' %}

{% block content %}

<section class="page-section" >
    <div class="container">
        <!-- Contact Section Heading-->
        <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">서비스 종류</h2>
        <!-- Icon Divider-->
        <div class="divider-custom">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>
        <!-- Contact Section Form-->
        <div class="row justify-content-center">
            <div class="d-flex justify-content-center">
                <form method="POST" action="{% url 'Camera_app:fileupload' %}" enctype="multipart/form-data">
                {% csrf_token %}
        <!--        <input type="submit" class="btn btn-primary col-12" value="제출">-->
                <input type="file" accept="image/*;capture=camera" name="Camera"  id="Camera" style="display:none;" required >
                <input type="hidden" name="lat" id="lat">
                <input type="hidden" name="long" id="long">
                <button type="button" class="btn btn-primary btn-xl" style="margin-bottom:2%;" id="testButton" >주차가능구역 판별</button>
                    <button type="submit" class="btn btn-secondary" style="display:none;margin-bottom:2%" id="distinguishButton" >전송</button >
                </form>
            </div>
            <div class="d-flex justify-content-center">
                <a src="{% url 'geolocation_app:geolocation' %}" class="btn btn-primary btn-xl" id="guideButton" >가까운 전동킥보드 주차장 안내</a >
                </div>
            </div><!--button태그의 class에서 disabled 삭제-->
        </div>

        </div>

    </div>
    </section>

<!--</body>-->

{% endblock content%}

{% block javascripts %}
    <script src="https://code.getmdl.io/1.3.0/material.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dialog-polyfill/0.5.0/dialog-polyfill.js" charset="utf-8"></script>
    <script >
    //var url = "{% url 'Camera_app:fileupload' %}";
    // var user_id = "xxxx";
    function success(position) {
        const latitude  = position.coords.latitude;
        const longitude = position.coords.longitude;
        // window.onload = function(){

        document.getElementById("lat").value=latitude;
        document.getElementById("long").value=longitude;
        //}

        //window.location=url + "?" +"latitude=" + latitude + "&" + "longitude=" + longitude;
    }
    function error(position) {
            //HTTPS가 아니거나 위치수집 동의를 안 할 경우
            alert("위치수집 동의를 해주세요")

        }

    if(!navigator.geolocation) {
        //Geolocation API를 지원하지 않는 브라우저일 경우
        alert(" 현 브라우저가 위치수집을 지원하지 않습니다.\n 다른 브라우저를 이용해주세요 ")

        } else {
        //Geolocation API를 지원하는 브라우저일 경우

        var optn = {enableHighAccuracy : true, timeout : 30000, maximumage: 0};
        function geolocation(){
                navigator.geolocation.getCurrentPosition(success, error,optn);
            }
        }
     $(document).ready(geolocation());

     $(document).on("click", "#testButton", function() {
        $("#Camera").click();
        $("#distinguishButton").css("display", "inline-block");
     });

    </script>
{% endblock javascripts %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% include 'includes/head.html' %}
<body>
    {% include 'includes/navigation.html' %}
    <header class="masthead bg-primary text-white text-center">
        <div class="container">
            <h1>서비스 이름</h1>
        </div>
    </header>


    {% block content %}{% endblock content %}

    {% include 'includes/footer.html' %}

    {% block javascripts %}{% endblock javascripts %}


</body>
</html>

templates/includes/footer.html
{% load static %}
<footer class="footer text-center">
    <div class="container">
        <div class="row justify-content-center">
            <div class="d-flex justify-content-center mb-3">
                <a href="#page-top">
                    <img class="navbar-brand" src="{% static 'assets/img/PZone_logo.png' %}" width="30" height="30">
                </a>
                <p class="text-uppercase mb-4">PZone</p>
            </div>
        </div>
    </div>

    <!-- Copyright Section-->
    <div class="copyright py-4 text-center text-white">
        <div class="container"><small>Copyright &copy; Your Website 2022</small></div>
    </div>
</footer>

templates/includes/head.html
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>PZONE - {% block title %}{% endblock %}</title>
    
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}">

    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <!-- Core theme CSS (includes Bootstrap)-->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

templates/includes/scripts.html
{% load static %}
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://apis.openapi.sk.com/tmap/jsv2?version=1&appKey=l7xx0ffb87c22bdb45ae8facaeeb7958ad36"></script>